#name: notiongit
#on:
#  workflow_dispatch:
#jobs:
#  auto-sync-from-notion-to-github:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Notion2Github
#        uses: 43-stuti/notion-github@v1.3
#        with:
#          SECRET_GITHUB: ${{secrets.TOKEN_GITHUB}}
#          NOTION_SECRET: ${{secrets.TOKEN_NOTION}}
#          OWNER: 'nature-of-code'
#          REPO: 'noc-notion'
#          BLOCK_NAME: 'Book'